repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-case-conflict
      - id: mixed-line-ending
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.22
    hooks:
      - id: typos

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py312-plus"]
        files: ".*"

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.341
    hooks:
      - id: pyright
        exclude: "tests"
        additional_dependencies:
          [
            fastapi,
            faker,
            pydantic>=2,
            pytest,
            sqlalchemy>=2,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: "tests"
        additional_dependencies:
          [
            fastapi,
            faker,
            pydantic>=2,
            pytest,
            sqlalchemy>=2,
          ]

  - repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      stages: [commit]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
