services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
    command: redis-server --requirepass ${REDIS_DEFAULT_PASS}  # --notify-keyspace-events Ex
    env_file:
      - .env
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: "postgres"
    ports:
      - "${DEFAULT_DB_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DEFAULT_DB_PASSWORD}
      - POSTGRES_USER=${DEFAULT_DB_USER}
      - POSTGRES_DB=${DEFAULT_DB_NAME}
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: "rabbitmq"
    restart: unless-stopped
    ports:
      - "${MQ_AMQP_PORT}:5672"
      - "${MQ_MGMT_PORT}:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_DEFAULT_PASS}
    env_file:
      - .env
  # app:
  #   depends_on:
  #     - redis
  #     - postgres
  #     - rabbitmq
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: "app"
  #   restart: unless-stopped
  #   ports:
  #     - "${APP_PORT}:8000"
  #   volumes:
  #     - ./data/app:/var/lib/app
